//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGarageMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public System.Guid LocationId { get; set; }
        public bool Active { get; set; }
        public string SharedSecret { get; set; }
        public string SharedIV { get; set; }
        public string Password { get; set; }
        public string LocationName { get; set; }
    }
}
